
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Wim Brittijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Wim Korf	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Mariette Korf-Frohn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Ria Clijnk	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Cees Clijnk	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Annie Hooft-Mazenier	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Francina Hooft	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Ali van Loenen	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Truus Kuijt	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Steven Kuijt	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Willem-Peter Koelewijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Eef van Dijk	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Peter Koelewijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Henk Meester	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Grietje Meester-vd Geest	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Teuny Heinen-Koelewijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Jan Anbeek	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Lex van Bemmel	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Nora van Bemmel	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Frans Böhm	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Paul Bos	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Janny van Gulik- van Schaik	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Fanny Bouman-Beaux	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Pieter Hop	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Jaap de Graaf	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Harry van der Heijden	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Rudi Rutgers	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Sino van der Heide	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Ineke van der Heide	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Roel Huisman	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Jannie Koelewijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Steven Koelewijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Kees Koelewijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Arjan Kok	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Hillie van Ouwerkerk	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Gerard van Ouwerkerk	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Fridjof de Rijke	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Sietse Luppen	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Jorge Vinck	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Marijke Bus-van Neerijnen	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Ellen Starreveld	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Henk Starreveld	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Hans Bus	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Geessien Heinen-Koelewijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Hilco de Graaf	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Joke Poel-de Haan	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Meep Poel	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Gr&#233 Dieleman	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Hans Hover	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Lies Hover - van IJzendoorn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Erik Hendrikx	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Petra Hendrikx-Heijkoop	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Michael Thomas	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Wout Koelewijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Klaas Heijnen	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Piet Knoester	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Jan Koelewijn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Jan van Goor	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Hille de Graaf	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Rita Reyn	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Monique Knoester	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Wouter ter Haar	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Hennie ter Haar-Zaal	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'An Spriel-van Renswoude	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Arie Spriel	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Lenie Dreijer	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Tijmen de Jong	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Henk Opstelten	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Dick Roose	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Maria Malestein - van Rossum	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Boudewijn Hessel	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Loes van Diermen - Ruizendaal	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Cees Hopman	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Riek Hopman	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Wouter Heinen	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Coby Huisman-Scheltens	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Wim de Graaf	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Sushila van Diermen	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Ronald van Mondfrans	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Mia van Mondfrans	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Gerina Kok	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Renk Koelewijn-Beekhuis	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Aart Hop	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Willemijn Martensen-Hop	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Louise Gerarda van t Velt	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Adrie Talen	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Theo Zijl	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Ruud ter Haar	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Corrie ter Haar	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Frans van Neerijnen	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Lies van Maurik - Verbij	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Bram van Diermen	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Elly Maissan-vd Knaap	'); 
insert into hussel_spelers (Id, Vereniging_id,Naam) values (0,4,'Willy Roose-Lucas	'); 
